image: maven:3-amazoncorretto-21-debian

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  GIT_STRATEGY: "clone"

cache:
  paths:
    - .m2/

stages:
  - test

test-backend:
  stage: test
  script:
    - cd backend
    - mvn -B clean install

test-frontend:
  image: node:20
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm run build
    - npm run lint

